const productTypes = {
    SET_ATTRIBUTES: 'SET_ATTRIBUTES',
    SET_VARIATIONS_SELECTED: 'SET_VARIATIONS_SELECTED',
    SET_PRODUCT_SELECTED: 'SET_PRODUCT_SELECTED',
    SET_PRODUCT_PRICE: 'SET_PRODUCT_PRICE',
    SET_IS_UNIQUE_PRODUCT: 'SET_IS_UNIQUE_PRODUCT',
    SET_IS_IN_STOCK_PRODUCT: 'SET_IS_IN_STOCK_PRODUCT',
    SET_TITLE_MAIN_PRODUCT: 'SET_TITLE_MAIN_PRODUCT',
    SET_RAW_PRODUCT_DATA: 'SET_RAW_PRODUCT_DATA',
    SET_IS_IN_THE_CART_PRODUCT: 'SET_IS_IN_THE_CART_PRODUCT',
}

export default productTypes;