const productTypes = {
  SET_VARIATIONS_SELECTED: "SET_VARIATIONS_SELECTED",
  SET_PRODUCT_SELECTED: "SET_PRODUCT_SELECTED",

  SET_IS_IN_STOCK_PRODUCT: "SET_IS_IN_STOCK_PRODUCT",

  SET_RAW_PRODUCT_DATA: "SET_RAW_PRODUCT_DATA",
  SET_IS_IN_THE_CART_PRODUCT: "SET_IS_IN_THE_CART_PRODUCT",
  SET_LIST_VARIATIONS: "SET_LIST_VARIATIONS",
  SET_PRODUCT_IS_VARIABLE: "SET_PRODUCT_IS_VARIABLE",
  SET_PRODUCT_IS_INDIVIDUAL: "SET_PRODUCT_IS_INDIVIDUAL",
  SET_PRODUCT_GALLERY_IMAGE: "SET_PRODUCT_GALLERY_IMAGE",
  SET_PRODUCT_VIDEO_PRESENTATION: "SET_PRODUCT_VIDEO_PRESENTATION",
  SET_MULTI_PRICE:'SET_MULTI_PRICE',
  SET_ON_SALE: "SET_ON_SALE",
};

export default productTypes;
