
const searchTypes = {
    SET_SEARCH_TERMS:"SET_SEARCH_TERMS",
    SET_RESULTS:"SET_RESULTS",
    SET_IS_LOADING:"SET_IS_LOADING",
    SET_IS_DONE: "SET_IS_DONE",
    SET_SHOW_RESULTS_SCREEN:"SET_SHOW_RESULTS_SCREEN",
    SET_SHOW_SEARCH_BAR:"SET_SHOW_SEARCH_BAR"
}

export default searchTypes;