const orderTypes = {
    SET_SHIPPEMENT_MODE_SELECTED: 'SET_SHIPPEMENT_MODE_SELECTED',
    SET_SHIPPEMENT_DATA: 'SET_SHIPPEMENT_DATA',
    SET_LIST_SHIPPEMENT_AVAILABLE: 'SET_LIST_SHIPPEMENT_AVAILABLE',
    SET_SHIPPEMENT_DATA_VALIDATION_STATE: 'SET_SHIPPEMENT_DATA_VALIDATION_STATE',
    SET_TOTAL_PRICE: 'SET_TOTAL_PRICE',



}

export default orderTypes